const $=s=>document.querySelector(s);const state={sessions:[],providers:[],models:{},active:null,lastMessages:"",panel:null};
async function api(path,options={}){const r=await fetch(`/api/v1${path}`,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(r.status===204)return null;const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`${r.status} ${r.statusText}`);return data}
function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
async function loadProviders(){const data=await api("/providers");state.providers=data.profiles||[];const sel=$("#provider-select");sel.replaceChildren(new Option("Choose provider",""));state.providers.forEach(p=>sel.add(new Option(p.name,p.id)));if(state.active)sel.value=state.active.provider||"";await loadModels(false)}
async function loadModels(scan=false){const sel=$("#model-select"),pid=$("#provider-select").value,current=state.active?.model||"";const render=models=>{sel.replaceChildren(new Option("Choose model",""));models.forEach(m=>sel.add(new Option(m.id,m.id)));sel.add(new Option("Enter model ID…","__manual"));if(current){if(![...sel.options].some(o=>o.value===current))sel.add(new Option(current,current));sel.value=current}};if(!pid){render([]);return}if(state.models[pid])render(state.models[pid]);else render([]);if(scan||!state.models[pid]){try{const models=await api(`/providers/${pid}/models`);state.models[pid]=models;render(models);toast(`Found ${models.length} models`)}catch(e){toast(`Model scan failed: ${e.message}`)}}}
async function loadSessions(){state.sessions=await api("/sessions");renderSessions();if(state.active){const found=state.sessions.find(x=>x.id===state.active.id);if(found)state.active=found}}
function renderSessions(){const nav=$("#sessions");nav.replaceChildren();state.sessions.forEach(s=>{const item=node("div",`session-item ${s.id===state.active?.id?"active":""} ${s.status||""}`);item.dataset.id=s.id;const title=node("strong","",s.title);const del=node("button","","×");del.title="Delete session";del.style.cssText="box-shadow:none;background:transparent;padding:0";del.onclick=async ev=>{ev.stopPropagation();if(confirm(`Move “${s.title}” to trash?`)){try{await api(`/sessions/${s.id}`,{method:"DELETE"});if(state.active?.id===s.id)selectSession(null);await loadSessions()}catch(e){toast(e.message)}}};item.append(title,del,node("small","",s.model||"No model"),node("span","dot"));item.onclick=()=>selectSession(s);nav.append(item)})}
async function newSession(){const preferred=state.providers[0];const s=await api("/sessions",{method:"POST",body:JSON.stringify({title:"New session",provider:preferred?.id||"",model:""})});await loadSessions();await selectSession(s)}
async function selectSession(s){state.active=s;state.lastMessages="";renderSessions();const has=!!s;$("#empty").classList.toggle("hidden",has);$("#chat").classList.toggle("hidden",!has);$("#composer").classList.toggle("hidden",!has);$("#session-title").disabled=!has;$("#session-title").value=s?.title||"Select or create a session";$("#provider-select").value=s?.provider||"";if(has){await loadModels(false);$("#model-select").value=s.model||"";await pollActive()}}
function renderMessages(messages){const key=JSON.stringify(messages.map(m=>[m.id,m.content]));if(key===state.lastMessages)return;state.lastMessages=key;const chat=$("#chat");chat.replaceChildren();messages.forEach(m=>{const box=node("article",`message ${m.role}`);box.append(node("span","meta",m.role==="tool"?`tool · ${m.name}`:`${m.role}${m.model?` · ${m.model}`:""}`),document.createTextNode(m.content|| (m.tool_calls?"Calling local tools…":"")));chat.append(box)});chat.scrollTop=chat.scrollHeight}
async function pollActive(){if(!state.active)return;try{const data=await api(`/sessions/${state.active.id}`);state.active=data.session;renderMessages(data.messages||[]);const status=data.task?.status||"idle";const pill=$("#task-state");pill.textContent=status+(data.task?.tool_calls?` · ${data.task.tool_calls} tools`:"");pill.className=`pill ${status}`;$("#stop").classList.toggle("hidden",status!=="running");const list=state.sessions.find(x=>x.id===state.active.id);if(list)list.status=status;renderSessions()}catch(e){console.error(e)}}
$("#composer").onsubmit=async e=>{e.preventDefault();const p=$("#prompt"),content=p.value.trim();if(!content||!state.active)return;p.value="";try{await api(`/sessions/${state.active.id}/messages`,{method:"POST",body:JSON.stringify({content})});await pollActive()}catch(e){toast(e.message)}};
$("#prompt").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#composer").requestSubmit()}};
$("#stop").onclick=async()=>{if(state.active)await api(`/sessions/${state.active.id}/stop`,{method:"POST"})};
$("#session-title").onchange=async e=>{if(!state.active)return;state.active=await api(`/sessions/${state.active.id}`,{method:"PATCH",body:JSON.stringify({title:e.target.value})});await loadSessions()};
$("#provider-select").onchange=async e=>{if(!state.active){return}state.active=await api(`/sessions/${state.active.id}`,{method:"PATCH",body:JSON.stringify({provider:e.target.value})});await loadModels(true)};
$("#model-select").onchange=async e=>{if(!state.active)return;let model=e.target.value;if(model==="__manual"){model=prompt("Enter the exact model ID")?.trim()||state.active.model||"";if(![...e.target.options].some(o=>o.value===model))e.target.add(new Option(model,model));e.target.value=model}state.active=await api(`/sessions/${state.active.id}`,{method:"PATCH",body:JSON.stringify({model})})};
$("#new-session").onclick=$("#empty-new").onclick=newSession;$("#refresh").onclick=loadSessions;$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");
function openPanel(type){state.panel=type;$(".sidebar").classList.remove("open");$("#panel").classList.remove("hidden");$("#panel-title").textContent=type[0].toUpperCase()+type.slice(1);if(type==="settings")settingsPanel();if(type==="skills")skillsPanel();if(type==="terminal")terminalPanel()}
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$("#panel-close").onclick=()=>$("#panel").classList.add("hidden");
function field(label,type="text",value=""){const wrap=node("div","field"),l=node("label","",label),i=node("input");i.type=type;i.value=value;wrap.append(l,i);return[wrap,i]}
function settingsPanel(){const body=$("#panel-body");body.replaceChildren();const card=node("div","card"),h=node("h3","","Add provider");const presets={"Custom / OmniRoute":"","OpenAI":"https://api.openai.com/v1/","OpenRouter":"https://openrouter.ai/api/v1/","xAI":"https://api.x.ai/v1/","Groq":"https://api.groq.com/openai/v1/","Mistral":"https://api.mistral.ai/v1/","Ollama":"http://127.0.0.1:11434/v1/"};const presetWrap=node("div","field"),presetLabel=node("label","","Provider preset"),preset=node("select");Object.keys(presets).forEach(x=>preset.add(new Option(x,x)));presetWrap.append(presetLabel,preset);const [n,ni]=field("Profile name","text","OmniRoute"),[u,ui]=field("OpenAI-compatible base URL","url",""),[k,ki]=field("API key","password",""),[mp,mpi]=field("Models path","text","models");preset.onchange=()=>{ui.value=presets[preset.value];if(preset.value!=="Custom / OmniRoute")ni.value=preset.value};const note=node("p","","Anthropic and Gemini native adapters are tracked in the next provider milestone; the current runtime never mocks an unsupported adapter.");note.style.color="var(--muted)";const save=node("button","primary","Save provider");save.onclick=async()=>{try{const saved=await api("/providers",{method:"POST",body:JSON.stringify({name:ni.value,type:"openai-compatible",base_url:ui.value,api_key:ki.value,models_path:mpi.value,chat_path:"chat/completions"})});ki.value="";delete state.models[saved.id];await loadProviders();if(state.active){state.active=await api(`/sessions/${state.active.id}`,{method:"PATCH",body:JSON.stringify({provider:saved.id})});$("#provider-select").value=saved.id;await loadModels(true)}else{const models=await api(`/providers/${saved.id}/models`);state.models[saved.id]=models;toast(`Provider saved · found ${models.length} models`)}}catch(e){toast(e.message)}};card.append(h,presetWrap,n,u,k,mp,note,save);body.append(card);state.providers.forEach(p=>{const c=node("div","card");c.append(node("strong","",p.name),node("p","",p.base_url));body.append(c)})}
async function skillsPanel(){const body=$("#panel-body");body.replaceChildren(node("p","","Loading local skills…"));try{const skills=await api("/skills");body.replaceChildren();const install=node("div","card"),h=node("h3","","Install skill"),[src,srci]=field("Git URL, local directory, or .zip path"),[nm,nmi]=field("Optional name"),btn=node("button","primary","Inspect & install locally");btn.onclick=async()=>{try{await api("/skills",{method:"POST",body:JSON.stringify({source:srci.value,name:nmi.value})});toast("Skill installed");skillsPanel()}catch(e){toast(e.message)}};install.append(h,src,nm,btn);body.append(install);skills.forEach(sk=>{const c=node("div","card"),row=node("div","row"),text=node("div");text.append(node("strong","",sk.name),node("p","",sk.description||sk.source));const del=node("button","danger","Uninstall");del.onclick=async()=>{if(confirm(`Uninstall ${sk.name}?`)){await api(`/skills/${encodeURIComponent(sk.name)}`,{method:"DELETE"});skillsPanel()}};row.append(text,del);c.append(row);body.append(c)})}catch(e){body.textContent=e.message}}
function terminalPanel(){const body=$("#panel-body");body.replaceChildren();const note=node("p","","Commands run in the local workspace through the Go daemon. Interactive PTY transport is the next platform milestone."),out=node("pre","terminal","Arka local terminal ready.\n"),input=node("input","terminal-input");input.placeholder="Enter a command and press Enter";input.onkeydown=async e=>{if(e.key!=="Enter")return;const cmd=input.value.trim();if(!cmd)return;input.value="";out.textContent+=`\n$ ${cmd}\n`;try{const r=await api("/terminal/exec",{method:"POST",body:JSON.stringify({command:cmd})});out.textContent+=r.output+(r.error?`\n${r.error}`:"");out.scrollTop=out.scrollHeight}catch(err){out.textContent+=err.message}};body.append(note,out,input)}
setInterval(()=>{if(state.active)pollActive();loadSessions().catch(()=>{})},1600);
(async()=>{try{await loadProviders();await loadSessions();$("#connection").textContent="● local daemon"}catch(e){$("#connection").textContent="● disconnected";toast(e.message)}})();
